### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by HyperGroups** [Tencent/angel#113]
17/06/28 16:00:39 INFO yarn.AngelYarnClient: Command to launch container for ApplicationMaster is : $JAVA_HOME/bin/java -Dlog4j.configuration=log/angel.properties -Dlog4j.logger.com.tencent.ml=DEBUG -Dyarn.app.container.log.dir=<LOG_DIR> -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Xmx1024m com.tencent.angel.master.AngelApplicationMaster 1><LOG_DIR>/stdout 2><LOG_DIR>/stderr 
17/06/28 16:00:39 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  default
17/06/28 16:00:39 INFO impl.YarnClientImpl: Submitted application application_1498124481939_0016
17/06/28 16:00:45 INFO yarn.AngelYarnClient: appMaster getTrackingUrl = http://stghadoop1:8088/cluster/app/application_1498124481939_0016/
17/06/28 16:00:45 INFO yarn.AngelYarnClient: master host=10.12.101.245, port=23469
17/06/28 16:00:45 INFO yarn.AngelYarnClient: start to create rpc client to am
17/06/28 16:02:00 ERROR yarn.AngelYarnClient: submit application to yarn failed.
com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.12.101.245:23469
最基本的example没跑通，这个要怎么解决，另10.12.101.245并不是yarn集群的master

**Comment by paynie** [comment]
Thanks for reporting this issues.  IYou can open `http://stghadoop1:8088/cluster/app/application_1498124481939_0016/` to find detail failed message and paste here.  `10.12.101.245` is the location of Master of Angel.

**Comment by HyperGroups** [comment]
PSAttempt_0_0 failed due to: Exception from container-launch.
Container id: container_1498124481939_0018_01_000002
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
at org.apache.hadoop.util.Shell.run(Shell.java:478)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 1
PSAttempt_0_1 failed due to: Exception from container-launch.
Container id: container_1498124481939_0018_01_000003
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
at org.apache.hadoop.util.Shell.run(Shell.java:478)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 1
PSAttempt_0_2 failed due to: Exception from container-launch.
Container id: container_1498124481939_0018_01_000004
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
at org.apache.hadoop.util.Shell.run(Shell.java:478)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 1
PSAttempt_0_3 failed due to: Exception from container-launch.
Container id: container_1498124481939_0018_01_000005
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
at org.apache.hadoop.util.Shell.run(Shell.java:478)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 1

**Comment by lshmouse** [comment]
@HyperGroups  请在yarn 找一下container(container_1498124481939_0018_01_000002)的详细日志

**Comment by paynie** [comment]
@HyperGroups  It seems that  yarn start ps failed. This  error is commonly caused by parameter format error or some  environments (such as JDK) are not valid. You can find the error message in ps container log use the method in [FAQ](https://github.com/Tencent/angel/wiki/Angel%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by HyperGroups** [comment]
@lshmouse 请问哪里有此container的详细日志？
@paynie 参照wiki打开后，只有如下的一小些内容，没有更多的日志内容

---
Total Vmem allocated for Containers	2.10 GB
Vmem enforcement enabled	false
Total Pmem allocated for Container	1 GB
Pmem enforcement enabled	true
Total VCores allocated for Containers	8
NodeHealthyStatus	true
LastNodeHealthTime	Thu Jun 29 11:37:00 CST 2017
NodeHealthReport	
Node Manager Version:	2.6.0-cdh5.7.1 from ae44a8970a3f0da58d82e0fc65275fff8deabffd by jenkins source checksum 839cebff6368a8752e3e97b7d29713df on 2016-06-01T23:32Z
Hadoop Version:	2.6.0-cdh5.7.1 from ae44a8970a3f0da58d82e0fc65275fff8deabffd by jenkins source checksum 298b68dc3b308983f04cb37e8416f13 on 2016-06-01T23:25Z


----
Redirecting to log server for container_ 1498124481939_ 0018_ 01_ 000001
ResourceManager
RM Home
NodeManager
Tools
java.lang.Exception:Unknown container.Container either has not started or has already completed or doesn't belong to this node at all.

**Comment by HyperGroups** [comment]
目前这个问题有所进展
17/06/29 18:32:38 INFO yarn.AngelYarnClient: start pss success
17/06/29 18:32:38 INFO ps.PSPartitioner: blockRow = 1, blockCol=5000000
17/06/29 18:32:38 INFO protobuf.ProtobufUtil: Matrix lr_weight partition num: 2
17/06/29 18:32:38 INFO ps.PSPartitioner: blockRow = 1, blockCol=50
17/06/29 18:32:38 INFO protobuf.ProtobufUtil: Matrix lr_loss partition num: 1

之前看到`Unsupported major.minor version 52.0`的报错是系统有的机器java版本是1.7导致。
后来改成了1.8，之后就看到不到此报错，焦点是最开始楼层的报错，同时Local模式能跑通。
后来进行了一些操作，又看到了这个`Unsupported major.minor version 52.0`的报错，
然后进行一些尝试操作：下载最新版的JDK1.8，并在启动脚本里按wiki里说明指定JAVA_HOME的地址，并重新把几台测试机器的配置统一处理了一下。

**Comment by binmu123** [comment]
我的本地local模式跑的没有问题，可以正常执行，但是yarn模式时就有错误
17/06/30 02:37:56 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  default
17/06/30 02:37:56 INFO impl.YarnClientImpl: Submitted application application_1498790102869_0001
17/06/30 02:37:59 INFO yarn.AngelYarnClient: appMaster getTrackingUrl = http://b0c5e9cf3648:8088/cluster/app/application_1498790102869_0001/
17/06/30 02:37:59 INFO yarn.AngelYarnClient: master host=172.16.16.20, port=28343
17/06/30 02:37:59 INFO yarn.AngelYarnClient: start to create rpc client to am
17/06/30 02:42:55 ERROR yarn.AngelYarnClient: submit application to yarn failed.
com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /172.16.16.20:28343
	at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:312)
	at com.sun.proxy.$Proxy14.getAllPSLocation(Unknown Source)
	at com.tencent.angel.client.AngelClient.waitForAllPS(AngelClient.java:710)
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:167)
	at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:46)
	at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
	at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
	at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:90)
	at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:28)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:124)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:110)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:110)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /172.16.16.20:28343

从start to create rpc client to am  处开始卡壳，但是我的local模式时没有问题，rpc可以与am连接，正常运行。
我的启动命令是
./angel-submit \
 	--angel.app.submit.class "com.tencent.angel.ml.classification.lr.LRRunner"\
 	--angel.train.data.path "hdfs://localhost:9000/project/test/lr_data" \
 	--angel.log.path "hdfs://localhost:9000/project/test/log" \
 	--angel.save.model.path "hdfs://localhost:9000/project/test/model" \
 	--action.type train \
 	--ml.data.type libsvm \
 	--ml.feature.num 1024 \
 	--angel.job.name LR_test
我的hadoop是standalone的，求解答

**Comment by lshmouse** [comment]
@HyperGroups  看看一下 application_1498790102869_0001 的container是否启动失败，发一下具体日志。只看客户端是看不出具体问题的

**Comment by HyperGroups** [comment]
经过一翻折腾，测试例子LRTest
yarn模式跑通一次。
可以加大数据量测试了。

**Comment by binmu123** [comment]
@HyperGroups   你好，你碰到过我这种问题吗？  rpc连接am失败，local模式可以 但是yarn模式rpc连接超时

**Comment by HyperGroups** [comment]
@binmu123 本帖子就是你所遇到的问题，试着设置下java_home在启动脚本里。

**Comment by binmu123** [comment]
好的，谢谢 我试试

**Comment by binmu123** [comment]
@HyperGroups   你好，我的java版本应该没有问题，是1.8。
我刚才也设置了一下，但是仍然是从start to create rpc client to am 处开始卡壳。连接不上
是不是我hadoop集群的问题，hadoop和yarn我就搭了一个单点做测试一下，都是standalone模式，所有服务都在一个机子上。

**Comment by qdj0511** [comment]
@binmu123  我刚才测试了一下，确实在angel_submit上添加JAVA_HOME就能搞定。
