### ISSUE TITLE
Spark-on-angel implement LogisticRegression use user data throw exception

### ISSUE THREAD

**Issue by QingdiMeng** [Tencent/angel#138]
We change this spark-on-angel example, 
https://github.com/Tencent/angel/blob/master/spark-on-angel/examples/src/main/scala/com/tencent/angel/spark/examples/ml/LogisticRegression.scala
Then we change train data set input as a parquet file, which has schema like (label : Double,  features : VectorUDT) and change code like

    import org.apache.spark.ml.classification.ps.{LogisticRegression => PSLR}

    val dateSet = spark.read.parquet(/path/to/mysamples.snappy.parquet)
    val lr = new PSLR()
      .setLabelCol("label")
      .setFeaturesCol("features")
      .setRegParam(0.01)
      .setElasticNetParam(0.0)
      .setMaxIter(10)
      .setTol(1e-6)

We submit to yarn-cluster, and set num-texecuters to 10, 
We got this Exception in  LogisticRegression of spark-on-angel implementation.

`User class threw exception: java.lang.IllegalArgumentException: requirement failed: Nothing has been added to this summarizer.
at scala.Predef$.require(Predef.scala:224)
at org.apache.spark.mllib.stat.PSMultivariateOnlineSummarizer.variance(PSMultivariateOnlineSummarizer.scala:190)
at org.apache.spark.mllib.stat.PSMultivariateOnlineSummarizer.std(PSMultivariateOnlineSummarizer.scala:207)
at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:366)
at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:332)
at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:203)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
at com.xiaomi.angel.spark.examples.ml.LogisticRegressionSparkOnAngelExample$.run(LogisticRegressionSparkOnAngelExample.scala:50)
at com.xiaomi.angel.spark.examples.ml.LogisticRegressionSparkOnAngelExample$$anonfun$main$1.apply(LogisticRegressionSparkOnAngelExample.scala:19)
at com.xiaomi.angel.spark.examples.ml.LogisticRegressionSparkOnAngelExample$$anonfun$main$1.apply(LogisticRegressionSparkOnAngelExample.scala:17)
at com.tencent.angel.spark.examples.util.PSExamples$.runWithSparkContext(PSExamples.scala:50)
at com.xiaomi.angel.spark.examples.ml.LogisticRegressionSparkOnAngelExample$.main(LogisticRegressionSparkOnAngelExample.scala:17)
at com.xiaomi.angel.spark.examples.ml.LogisticRegressionSparkOnAngelExample.main(LogisticRegressionSparkOnAngelExample.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:648)`

**Comment by ZunwenYou** [comment]
The message shows that your input train data is empty, please print the count of DataFrame.
