### ISSUE TITLE
编译安装后，运行出现问题

### ISSUE THREAD

**Issue by hadp12345** [Tencent/angel#14]
我照着官网的步骤编译安装angel，但是测试运行出现了一些问题：
1、spark-on-angel-env.sh里ANGEL_VERSION指定的是1.1.8，但是编译后的jar包版本都是1.0.0的；

2、LOCAL运行./angel-example com.tencent.angel.example.SgdLRLocalExample时，
    （1）选择1时报错如下：
Exception in thread "main" java.lang.NoSuchMethodError: com.google.protobuf.LazyStringList.getUnmodifiableView()Lcom/google/protobuf/LazyStringList;
        at com.tencent.angel.protobuf.generated.ClientMasterServiceProtos$CheckMatricesCreatedRequest$Builder.buildPartial(ClientMasterServiceProtos.java:9294)
        at com.tencent.angel.protobuf.generated.ClientMasterServiceProtos$CheckMatricesCreatedRequest$Builder.build(ClientMasterServiceProtos.java:9283)
        at com.tencent.angel.client.AngelClient.waitForMatricesCreated(AngelClient.java:502)
        at com.tencent.angel.client.AngelClient.createMatrices(AngelClient.java:493)
        at com.tencent.angel.client.AngelClient.loadModel(AngelClient.java:164)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:47)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
        at com.tencent.angel.example.SgdLRLocalExample.trainOnLocalCluster(SgdLRLocalExample.java:103)
        at com.tencent.angel.example.SgdLRLocalExample.main(SgdLRLocalExample.java:168)
我发现在angel-ps的core下，com.tencent.angel.protobuf目录下确实没有generated这个目录，但是在angel-1.0.0-jar-with-dependencies.jar里面又有generated，我不清楚是什么情况。
    （2）当选择2时，bug如下:
Exception in thread "main" com.tencent.angel.exception.AngelException: java.io.IOException: matrix path file:/tmpmodel/lr_weight does not exist 
中间缺少一个"/"，因而找不到路径。

3、执行./SONA-example-local后,出现如下问题：
17/06/19 15:59:00 INFO AngelYarnClient: default FileSystem: hdfs://mycluster
17/06/19 15:59:00 INFO AngelYarnClient: libjarsDir=/tmp/hadoop-yarn/hadp/.staging/application_1497853469786_0002/libjars
17/06/19 15:59:00 INFO AngelYarnClient: libjars=
17/06/19 15:59:00 ERROR AngelYarnClient: submit application to yarn failed.
java.lang.IllegalArgumentException: Can not create a Path from an empty string
以上是我遇到的一些问题，希望能够得到帮助以解决问题

**Comment by paynie** [comment]
Thanks for reports these issues. Problem 2 can see also [SGDLR model problem](https://github.com/Tencent/angel/issues/6)

**Comment by paynie** [comment]
We use protobuf as the RPC protocol encoding format, and the code in the genereted directory is automatically generated by the protoc tool. The process of generating the code is called before the code is compiled, and the generated code is placed in the target directory of the angel-ps-core project. What version of protoc tool do you use? Is the code generated successfully? Maybe you can provide the log of the compilation process so that we can help you solve the problem.

**Comment by ZunwenYou** [comment]
1. the version bug have be fixed.
3. The log shows your application is running on Yarn;  if you  want to run example on yarn, you must use `SONA-example`

**Comment by paynie** [comment]
Protobuf version has been change to 2.5.0, which is compatible with official distribution packs of hadoop/spark, you can try again.

**Comment by hadp12345** [comment]
谢谢,我用Protobuf 2.5.0重新编译安装后大多数的例子都可以成功运行了，唯独运行SONA-example和SONA-example-local不行，前一个可能是我的配置不够，第一个application跑完后，第二个application卡在资源获取上；SONA-example-local还是之前的问题，不管我设置master是local，yarn还是spark：//xxx：7077，最后它都要得到libjars的值，但是状态显示为空值，最后提示java.lang.IllegalArgumentException: Can not create a Path from an empty string

**Comment by hadp12345** [comment]
SONA-example-local在我的机器上如果不指定master，默认会先连接standalone集群的master，然后再连接yarn的RM，我不清楚为什么它运行时会需要连接两个集群

**Comment by ZunwenYou** [comment]
加我们QQ群 20171688，或者直接加我QQ: 690863737 沟通会快一些。

**Comment by ZunwenYou** [comment]
You can try these two options:
1. do not set master parameter
2. set spark.master=local

Here is the [ source code](https://github.com/Tencent/angel/blob/branch-1.0.0/spark-on-angel/examples/src/main/scala/com/tencent/angel/spark/examples/ml/BreezeSGD.scala)

**Comment by hadp12345** [comment]
我设置spark.master=local后可以跑起来了，但是到后面还有错误
17/06/21 11:03:48 ERROR MatrixTransportClient: channel [id: 0xd1436291, L:0.0.0.0/0.0.0.0:38694 ! R:/172.16.11.243:23101] is not active
17/06/21 11:03:48 INFO App: write app report to file successfully jobReport {
  jobState: J_RUNNING
  curIteration: 0
  totalIteration: 100
  diagnostics: ""
}

17/06/21 11:03:48 INFO AngelApplicationMaster: write app state over
17/06/21 11:03:48 WARN AngelApplicationMaster: App Staging directory is null
17/06/21 11:03:48 INFO AngelApplicationMaster: Deleting tmp output directory file:/tmp/angel/application_1498014183314_-1716971708_51cc5e90-5b80-4904-a958-fcb9b92f4175
17/06/21 11:03:53 ERROR MatrixTransportClient: channel [id: 0x40b1b799, L:0.0.0.0/0.0.0.0:38697 ! R:/172.16.11.243:23101] is not active
17/06/21 11:03:58 INFO NettyServer: Stopping server on 24198
17/06/21 11:03:58 WARN MasterService: Heartbeat Timeout checker is interupted
17/06/21 11:03:58 INFO MasterService: WorkerPSService is stoped!
17/06/21 11:03:58 INFO AngelApplicationMaster: Exiting Angel AppMaster..GoodBye!
17/06/21 11:03:58 WARN LocalResourceManager: event handler is interrupted
17/06/21 11:03:58 INFO SparkUI: Stopped Spark web UI at http://172.16.11.243:4040
17/06/21 11:03:58 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/06/21 11:03:58 INFO MemoryStore: MemoryStore cleared
17/06/21 11:03:58 INFO BlockManager: BlockManager stopped
17/06/21 11:03:58 INFO BlockManagerMaster: BlockManagerMaster stopped
17/06/21 11:03:58 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/06/21 11:03:58 INFO SparkContext: Successfully stopped SparkContext
17/06/21 11:04:03 ERROR MatrixTransportClient: get channel failed 
io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /172.16.11.243:23101
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:257)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ZunwenYou** [comment]
This exception is thrown after the application finished. 
It do not affect to the result, and it only occur in spark on angel local mode.  
We will fix it soon @paynie , Thanks.
