### ISSUE TITLE
LRRunner train hung at model.clock.get in GradientDescent 

### ISSUE THREAD

**Issue by lshmouse** [Tencent/angel#145]
Runing LRRunner in yarn with config:     --angel.worker.task.number 4 and the train hung at model.clock.get in GradientDescent.

See jstack 

```
"pool-8-thread-4" #579 prio=5 os_prio=0 tid=0x00007f28f1a88000 nid=0x28c31 waiting on condition [0x00007f28b06f2000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000054dac7cc8> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.tencent.angel.psagent.matrix.transport.FutureResult.get(FutureResult.java:54)
        at com.tencent.angel.ml.optimizer.sgd.GradientDescent$.miniBatchGD(GradientDescent.scala:80)
        at com.tencent.angel.ml.classification.lr.LRLearner.trainOneEpoch(LRLearner.scala:72)
        at com.tencent.angel.ml.classification.lr.LRLearner.train(LRLearner.scala:103)
        at com.tencent.angel.ml.classification.lr.LRTrainTask.train(LRTrainTask.scala:55)
        at com.tencent.angel.worker.task.TrainTask.run(TrainTask.scala:28)
        at com.tencent.angel.worker.task.Task.runUser(Task.java:95)
        at com.tencent.angel.worker.task.Task.run(Task.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"pool-8-thread-3" #577 prio=5 os_prio=0 tid=0x00007f28f1a86000 nid=0x28c30 waiting on condition [0x00007f28b07f3000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000054dade4c8> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.tencent.angel.psagent.matrix.transport.FutureResult.get(FutureResult.java:54)
        at com.tencent.angel.ml.optimizer.sgd.GradientDescent$.miniBatchGD(GradientDescent.scala:80)
        at com.tencent.angel.ml.classification.lr.LRLearner.trainOneEpoch(LRLearner.scala:72)
        at com.tencent.angel.ml.classification.lr.LRLearner.train(LRLearner.scala:103)
        at com.tencent.angel.ml.classification.lr.LRTrainTask.train(LRTrainTask.scala:55)
        at com.tencent.angel.worker.task.TrainTask.run(TrainTask.scala:28)
        at com.tencent.angel.worker.task.Task.runUser(Task.java:95)
        at com.tencent.angel.worker.task.Task.run(Task.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
"pool-8-thread-2" #575 prio=5 os_prio=0 tid=0x00007f28f1a84800 nid=0x28c2f waiting on condition [0x00007f28b08f4000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at com.tencent.angel.psagent.matrix.transport.adapter.MatrixClientAdapter.waitForClock(MatrixClientAdapter.java:406)
        at com.tencent.angel.psagent.matrix.transport.adapter.MatrixClientAdapter.getRow(MatrixClientAdapter.java:154)
        at com.tencent.angel.psagent.consistency.ConsistencyController.getRow(ConsistencyController.java:100)
        at com.tencent.angel.psagent.matrix.MatrixClientImpl.getRow(MatrixClientImpl.java:53)
        at com.tencent.angel.ml.model.PSModel.getRow(PSModel.scala:203)
        at com.tencent.angel.ml.optimizer.sgd.GradientDescent$.miniBatchGD(GradientDescent.scala:36)
        at com.tencent.angel.ml.classification.lr.LRLearner.trainOneEpoch(LRLearner.scala:72)
        at com.tencent.angel.ml.classification.lr.LRLearner.train(LRLearner.scala:103)
        at com.tencent.angel.ml.classification.lr.LRTrainTask.train(LRTrainTask.scala:55)
        at com.tencent.angel.worker.task.TrainTask.run(TrainTask.scala:28)
        at com.tencent.angel.worker.task.Task.runUser(Task.java:95)
        at com.tencent.angel.worker.task.Task.run(Task.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by paynie** [comment]
Thanks. Is there any exception in log of this worker?  You can paste the log here.

**Comment by lshmouse** [comment]
@paynie  No exception log in this worker.

The last training logs are following

```
2017-07-14 14:59:49,815 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=3 validationData loss=3.053074162678633 precision=0.8823529411764706 auc=0.9047619047619048 trueRecall=0.6666666666666666 falseRecall=0.9285714285714286
2017-07-14 14:59:49,815 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=4 start.
2017-07-14 14:59:49,815 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=3 success. epoch cost 88 ms. train cost 87 ms. validation cost 1 ms.
2017-07-14 14:59:49,816 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=4 start.
2017-07-14 14:59:49,816 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=3 success. epoch cost 82 ms. train cost 79 ms. validation cost 3 ms.
2017-07-14 14:59:49,816 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=4 start.
2017-07-14 14:59:49,819 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=4 start.
2017-07-14 14:59:49,959 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=4 mini-batch update success. cost 138 ms. batch loss = 44.646960204827515
2017-07-14 14:59:49,960 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=4 trainData loss=41.1342586408435 precision=0.8827586206896552 auc=0.9230769230769231 trueRecall=0.6428571428571429 falseRecall=0.9401709401709402
2017-07-14 14:59:49,960 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=4 validationData loss=6.728718463866696 precision=0.7647058823529411 auc=0.7833333333333333 trueRecall=0.4 falseRecall=0.9166666666666666
2017-07-14 14:59:49,962 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=4 success. epoch cost 141 ms. train cost 138 ms. validation cost 3 ms.
2017-07-14 14:59:49,963 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=4 mini-batch update success. cost 147 ms. batch loss = 50.81669117047441
2017-07-14 14:59:49,964 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=5 start.
2017-07-14 14:59:49,964 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=4 trainData loss=47.54784506473975 precision=0.8571428571428571 auc=0.9272108843537415 trueRecall=0.8571428571428571 falseRecall=0.8571428571428571
2017-07-14 14:59:49,964 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=4 mini-batch update success. cost 149 ms. batch loss = 48.0636589828012
2017-07-14 14:59:49,964 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=4 validationData loss=9.745879920291227 precision=0.7058823529411765 auc=0.5952380952380952 trueRecall=0.6666666666666666 falseRecall=0.7142857142857143
2017-07-14 14:59:49,965 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=4 mini-batch update success. cost 149 ms. batch loss = 47.48791724699885
2017-07-14 14:59:49,965 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=4 trainData loss=43.782953762917714 precision=0.863013698630137 auc=0.9250965250965251 trueRecall=0.5142857142857142 falseRecall=0.972972972972973
2017-07-14 14:59:49,965 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=4 success. epoch cost 149 ms. train cost 147 ms. validation cost 2 ms.
2017-07-14 14:59:49,965 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=4 validationData loss=4.567618536216417 precision=0.9411764705882353 auc=0.7333333333333333 trueRecall=0.5 falseRecall=1.0
2017-07-14 14:59:49,965 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=4 trainData loss=43.74722873129453 precision=0.8424657534246576 auc=0.9217436974789915 trueRecall=0.5 falseRecall=0.9464285714285714
2017-07-14 14:59:49,966 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=4 validationData loss=2.9770103682425395 precision=0.8823529411764706 auc=0.9047619047619048 trueRecall=0.6666666666666666 falseRecall=0.9285714285714286
2017-07-14 14:59:49,966 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=5 start.
2017-07-14 14:59:49,966 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=4 success. epoch cost 151 ms. train cost 149 ms. validation cost 2 ms.
2017-07-14 14:59:49,966 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=4 success. epoch cost 150 ms. train cost 149 ms. validation cost 1 ms.
2017-07-14 14:59:49,967 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=5 start.
2017-07-14 14:59:49,967 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=5 start.
2017-07-14 14:59:50,054 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=5 mini-batch update success. cost 90 ms. batch loss = 44.18641124973904
2017-07-14 14:59:50,055 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=5 trainData loss=40.66408796223806 precision=0.8758620689655172 auc=0.9215506715506715 trueRecall=0.6071428571428571 falseRecall=0.9401709401709402
2017-07-14 14:59:50,055 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=5 validationData loss=6.6853245204676135 precision=0.7647058823529411 auc=0.7833333333333333 trueRecall=0.4 falseRecall=0.9166666666666666
2017-07-14 14:59:50,056 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=5 success. epoch cost 92 ms. train cost 90 ms. validation cost 2 ms.
2017-07-14 14:59:50,057 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=5 mini-batch update success. cost 90 ms. batch loss = 47.58336532306946
2017-07-14 14:59:50,058 INFO [pool-8-thread-3] com.tencent.angel.ml.classification.lr.LRLearner: Task[174]: epoch=6 start.
2017-07-14 14:59:50,058 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=5 trainData loss=43.391053979509365 precision=0.863013698630137 auc=0.9248391248391249 trueRecall=0.5142857142857142 falseRecall=0.972972972972973
2017-07-14 14:59:50,059 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=5 validationData loss=4.491927599233226 precision=0.9411764705882353 auc=0.7333333333333333 trueRecall=0.5 falseRecall=1.0
2017-07-14 14:59:50,059 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=5 mini-batch update success. cost 92 ms. batch loss = 47.07945393235572
2017-07-14 14:59:50,059 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=5 success. epoch cost 92 ms. train cost 91 ms. validation cost 1 ms.
2017-07-14 14:59:50,060 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=5 trainData loss=43.574953451041665 precision=0.8356164383561644 auc=0.9220063025210085 trueRecall=0.5 falseRecall=0.9375
2017-07-14 14:59:50,060 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=6 start.
2017-07-14 14:59:50,060 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=5 validationData loss=2.9294856415320187 precision=0.8823529411764706 auc=0.9047619047619048 trueRecall=0.6666666666666666 falseRecall=0.9285714285714286
2017-07-14 14:59:50,061 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=5 success. epoch cost 94 ms. train cost 92 ms. validation cost 2 ms.
2017-07-14 14:59:50,062 INFO [pool-8-thread-4] com.tencent.angel.ml.classification.lr.LRLearner: Task[175]: epoch=6 start.
2017-07-14 14:59:50,070 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=5 mini-batch update success. cost 104 ms. batch loss = 49.69109342801693
2017-07-14 14:59:50,071 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=5 trainData loss=46.89051976557198 precision=0.8571428571428571 auc=0.9276643990929705 trueRecall=0.8571428571428571 falseRecall=0.8571428571428571
2017-07-14 14:59:50,071 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=5 validationData loss=9.739984046762329 precision=0.7058823529411765 auc=0.619047619047619 trueRecall=0.6666666666666666 falseRecall=0.7142857142857143
2017-07-14 14:59:50,072 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=5 success. epoch cost 106 ms. train cost 105 ms. validation cost 1 ms.
2017-07-14 14:59:50,073 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=6 start.
2017-07-14 14:59:50,153 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=6 mini-batch update success. cost 80 ms. batch loss = 48.80921466822532
2017-07-14 14:59:50,153 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=6 trainData loss=46.353582406459886 precision=0.8571428571428571 auc=0.9283446712018141 trueRecall=0.8571428571428571 falseRecall=0.8571428571428571
2017-07-14 14:59:50,154 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=6 validationData loss=9.723205074470865 precision=0.7058823529411765 auc=0.619047619047619 trueRecall=0.6666666666666666 falseRecall=0.7142857142857143
2017-07-14 14:59:50,154 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=6 success. epoch cost 81 ms. train cost 80 ms. validation cost 1 ms.
2017-07-14 14:59:50,155 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=6 mini-batch update success. cost 95 ms. batch loss = 47.25361977504595
2017-07-14 14:59:50,155 INFO [pool-8-thread-2] com.tencent.angel.ml.classification.lr.LRLearner: Task[173]: epoch=7 start.
2017-07-14 14:59:50,155 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=6 trainData loss=43.11447732169637 precision=0.863013698630137 auc=0.9243243243243243 trueRecall=0.5428571428571428 falseRecall=0.963963963963964
2017-07-14 14:59:50,155 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=6 validationData loss=4.432351987752939 precision=0.9411764705882353 auc=0.7333333333333333 trueRecall=0.5 falseRecall=1.0
2017-07-14 14:59:50,156 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=6 success. epoch cost 96 ms. train cost 95 ms. validation cost 1 ms.
2017-07-14 14:59:50,157 INFO [pool-8-thread-1] com.tencent.angel.ml.classification.lr.LRLearner: Task[172]: epoch=7 start.
```

**Comment by paynie** [comment]
OK，you can contact me using QQ.

**Comment by lshmouse** [comment]
@paynie what's your QQ number?

**Comment by paynie** [comment]
https://github.com/Tencent/angel/issues/2
281122610

**Comment by lshmouse** [comment]
@andyyehoo Why is the issue closed? Has it been fixed? Thanks~
We rerun the job successfully with --angel.worker.task.number=1
