### ISSUE TITLE
Some problem of the example of spark on angel 

### ISSUE THREAD

**Issue by hbghhy** [Tencent/angel#160]
1.
When I run the SONA-example， when I use local mode or  SONA-example-local , the job seems work fine. And it will end with：
```
17/07/30 03:13:10 INFO ui.SparkUI: Stopped Spark web UI at http://127.0.0.1:4040
17/07/30 03:13:10 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/07/30 03:13:10 INFO memory.MemoryStore: MemoryStore cleared
17/07/30 03:13:10 INFO storage.BlockManager: BlockManager stopped
17/07/30 03:13:10 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
17/07/30 03:13:10 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/07/30 03:13:10 INFO spark.SparkContext: Successfully stopped SparkContext

```
But the process seems not end .... I have to input ctrl+C to end the script. Is it normal?

And when I run SONA-example,  it will throw:
```
17/07/30 03:26:26 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  root.default
17/07/30 03:26:26 ERROR yarn.AngelYarnClient: submit application to yarn failed.
org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1501399441343_0032 to YARN : Application application_1501399441343_0032 submitted by user h to unknown queue: root.default
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:271)
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:164)
	at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:99)
	at com.tencent.angel.spark.context.AngelPSContext$.submit(AngelPSContext.scala:248)
	at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:151)
	at com.tencent.angel.spark.PSContext$.liftedTree1$1(PSContext.scala:124)
	at com.tencent.angel.spark.PSContext$.instance(PSContext.scala:122)
	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:91)
	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:79)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:41)
	at com.tencent.angel.spark.examples.util.PSExamples$.runWithSparkContext(PSExamples.scala:50)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:41)
	at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" org.apache.spark.SparkException: PSContext init failed!
	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:92)
	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:79)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:41)
	at com.tencent.angel.spark.examples.util.PSExamples$.runWithSparkContext(PSExamples.scala:50)
	at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:41)
	at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```
Do i miss sth?

Here is my SONA-example:
```
#!/bin/bash

source ./spark-on-angel-env.sh

$SPARK_HOME/bin/spark-submit \
    --master local[2] \
    --conf spark.ps.jars=$SONA_ANGEL_JARS \
    --conf spark.ps.instances=1 \
    --conf spark.ps.cores=1 \
    --conf spark.ps.memory=512m \
    --jars $SONA_SPARK_JARS \
    --name "BreezeSGD-spark-on-angel" \
    --driver-memory 512m \
    --num-executors 1 \
    --executor-cores 1 \
    --executor-memory 512m \
    --class com.tencent.angel.spark.examples.ml.BreezeSGD \
    ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar
```
Here is my SONA-example-local:

```
source ./spark-on-angel-env.sh

$SPARK_HOME/bin/spark-submit \
    --jars $SONA_SPARK_JARS \
    --name "BreezeSGD-spark-on-angel" \
    --class com.tencent.angel.spark.examples.ml.BreezeSGD \
    ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar

```
2.When i want to run the test part in source code in package org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite with IDEA.
I delete the ignore tag . And I run follow part：
```

  test("logistic regression doesn't fit intercept when fitIntercept is off") {
    val lr = new LogisticRegression().setFamily("binomial")
    lr.setFitIntercept(false)
    val model = lr.fit(smallBinaryDataset)
    assert(model.intercept === 0.0)

    val mlr = new LogisticRegression().setFamily("multinomial")
    mlr.setFitIntercept(false)
    val mlrModel = mlr.fit(smallMultinomialDataset)
    assert(mlrModel.interceptVector === Vectors.sparse(3, Seq()))
  }
```

It will throw:
```
17/07/30 03:04:57 INFO AngelYarnClient: libjars=
17/07/30 03:04:57 ERROR AngelYarnClient: submit application to yarn failed.
java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
	at org.apache.hadoop.fs.Path.<init>(Path.java:135)
	at com.tencent.angel.client.yarn.AngelYarnClient.copyAndConfigureFiles(AngelYarnClient.java:255)
	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:150)
	at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:99)
	at com.tencent.angel.spark.context.AngelPSContext$.submit(AngelPSContext.scala:248)
	at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:151)
	at com.tencent.angel.spark.PSContext$.liftedTree1$1(PSContext.scala:124)
	at com.tencent.angel.spark.PSContext$.instance(PSContext.scala:122)
	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:91)
	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:350)
	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:332)
	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:203)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply$mcV$sp(LogisticRegressionSuite.scala:268)
	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply(LogisticRegressionSuite.scala:265)
	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply(LogisticRegressionSuite.scala:265)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite.org$scalatest$BeforeAndAfterAll$$super$run(LogisticRegressionSuite.scala:45)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite.run(LogisticRegressionSuite.scala:45)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

```

It seems i need to config some libpath in the ide? Can you tell what i need to do or give me some tutorial about it.
THX

**Comment by ZunwenYou** [comment]
1. `SONA-example-local` is a local mode for Spark on Angel, the problem which the progress can not finished by itself has fix in the latest version.
    The error when you run `SONA-example`  is `submitted by user h to unknown queue: root.default`, because there is no queue named `root.default` in your yarn cluster, you must set `spark.yarn.queue` parameter, which is given `root.default` as default value in our system.

**Comment by hbghhy** [comment]
THX, I can run the SONA-example and AngelPSContextSuite well. The SONA-example-local is not a big problem.

**Comment by ZunwenYou** [comment]
OK, I close this issue.

**Comment by JessicaAlphy** [comment]
### _The error when you run SONA-example is submitted by user h to unknown queue: root.default, because there is no queue named root.default in your yarn cluster, you must set spark.yarn.queue parameter, which is given root.default as default value in our system._ 
I encountered the same issue, where should I set the **spark.yarn.queue**,  could you please tell me in which file to set the "spark.yarn.queue"? 
I added the` --queue root.default \`  in the SONA-example file, but the task still failed.

**Comment by JessicaAlphy** [comment]
> 1. `SONA-example-local` is a local mode for Spark on Angel, the problem which the progress can not finished by itself has fix in the latest version.
>    The error when you run `SONA-example`  is `submitted by user h to unknown queue: root.default`, because there is no queue named `root.default` in your yarn cluster, you must set `spark.yarn.queue` parameter, which is given `root.default` as default value in our system.
> 2. Please have a look at `AngelPSContextSuite`, which can run successfully in IDEA.

I encountered the same issue, where should I set the spark.yarn.queue, could you please tell me in which file to set the "spark.yarn.queue"?
I added the` --queue root.default \ `in the SONA-example file, but the task still failed. Thank you very much.

**Comment by JessicaAlphy** [comment]
> When I run the SONA-example， when I use local mode or SONA-example-local , the job seems work fine. And it will end with：
> 
> ```
> 17/07/30 03:13:10 INFO ui.SparkUI: Stopped Spark web UI at http://127.0.0.1:4040
> 17/07/30 03:13:10 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
> 17/07/30 03:13:10 INFO memory.MemoryStore: MemoryStore cleared
> 17/07/30 03:13:10 INFO storage.BlockManager: BlockManager stopped
> 17/07/30 03:13:10 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
> 17/07/30 03:13:10 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
> 17/07/30 03:13:10 INFO spark.SparkContext: Successfully stopped SparkContext
> ```
> 
> But the process seems not end .... I have to input ctrl+C to end the script. Is it normal?
> 
> And when I run SONA-example, it will throw:
> 
> ```
> 17/07/30 03:26:26 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  root.default
> 17/07/30 03:26:26 ERROR yarn.AngelYarnClient: submit application to yarn failed.
> org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1501399441343_0032 to YARN : Application application_1501399441343_0032 submitted by user h to unknown queue: root.default
> 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:271)
> 	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:164)
> 	at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:99)
> 	at com.tencent.angel.spark.context.AngelPSContext$.submit(AngelPSContext.scala:248)
> 	at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:151)
> 	at com.tencent.angel.spark.PSContext$.liftedTree1$1(PSContext.scala:124)
> 	at com.tencent.angel.spark.PSContext$.instance(PSContext.scala:122)
> 	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:91)
> 	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:79)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:41)
> 	at com.tencent.angel.spark.examples.util.PSExamples$.runWithSparkContext(PSExamples.scala:50)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:41)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Exception in thread "main" org.apache.spark.SparkException: PSContext init failed!
> 	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:92)
> 	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:79)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:41)
> 	at com.tencent.angel.spark.examples.util.PSExamples$.runWithSparkContext(PSExamples.scala:50)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:41)
> 	at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> ```
> 
> Do i miss sth?
> 
> Here is my SONA-example:
> 
> ```
> #!/bin/bash
> 
> source ./spark-on-angel-env.sh
> 
> $SPARK_HOME/bin/spark-submit \
>     --master local[2] \
>     --conf spark.ps.jars=$SONA_ANGEL_JARS \
>     --conf spark.ps.instances=1 \
>     --conf spark.ps.cores=1 \
>     --conf spark.ps.memory=512m \
>     --jars $SONA_SPARK_JARS \
>     --name "BreezeSGD-spark-on-angel" \
>     --driver-memory 512m \
>     --num-executors 1 \
>     --executor-cores 1 \
>     --executor-memory 512m \
>     --class com.tencent.angel.spark.examples.ml.BreezeSGD \
>     ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar
> ```
> 
> Here is my SONA-example-local:
> 
> ```
> source ./spark-on-angel-env.sh
> 
> $SPARK_HOME/bin/spark-submit \
>     --jars $SONA_SPARK_JARS \
>     --name "BreezeSGD-spark-on-angel" \
>     --class com.tencent.angel.spark.examples.ml.BreezeSGD \
>     ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar
> ```
> 
> 2.When i want to run the test part in source code in package org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite with IDEA.
> I delete the ignore tag . And I run follow part：
> 
> ```
> 
>   test("logistic regression doesn't fit intercept when fitIntercept is off") {
>     val lr = new LogisticRegression().setFamily("binomial")
>     lr.setFitIntercept(false)
>     val model = lr.fit(smallBinaryDataset)
>     assert(model.intercept === 0.0)
> 
>     val mlr = new LogisticRegression().setFamily("multinomial")
>     mlr.setFitIntercept(false)
>     val mlrModel = mlr.fit(smallMultinomialDataset)
>     assert(mlrModel.interceptVector === Vectors.sparse(3, Seq()))
>   }
> ```
> 
> It will throw:
> 
> ```
> 17/07/30 03:04:57 INFO AngelYarnClient: libjars=
> 17/07/30 03:04:57 ERROR AngelYarnClient: submit application to yarn failed.
> java.lang.IllegalArgumentException: Can not create a Path from an empty string
> 	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
> 	at org.apache.hadoop.fs.Path.<init>(Path.java:135)
> 	at com.tencent.angel.client.yarn.AngelYarnClient.copyAndConfigureFiles(AngelYarnClient.java:255)
> 	at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:150)
> 	at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:99)
> 	at com.tencent.angel.spark.context.AngelPSContext$.submit(AngelPSContext.scala:248)
> 	at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:151)
> 	at com.tencent.angel.spark.PSContext$.liftedTree1$1(PSContext.scala:124)
> 	at com.tencent.angel.spark.PSContext$.instance(PSContext.scala:122)
> 	at com.tencent.angel.spark.PSContext$.getOrCreate(PSContext.scala:91)
> 	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:350)
> 	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:332)
> 	at org.apache.spark.ml.classification.ps.LogisticRegression.train(LogisticRegression.scala:203)
> 	at org.apache.spark.ml.Predictor.fit(Predictor.scala:96)
> 	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply$mcV$sp(LogisticRegressionSuite.scala:268)
> 	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply(LogisticRegressionSuite.scala:265)
> 	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite$$anonfun$7.apply(LogisticRegressionSuite.scala:265)
> 	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
> 	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
> 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 	at org.scalatest.Transformer.apply(Transformer.scala:22)
> 	at org.scalatest.Transformer.apply(Transformer.scala:20)
> 	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
> 	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
> 	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
> 	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
> 	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
> 	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
> 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
> 	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
> 	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
> 	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
> 	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
> 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
> 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
> 	at scala.collection.immutable.List.foreach(List.scala:381)
> 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
> 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
> 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
> 	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
> 	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
> 	at org.scalatest.Suite$class.run(Suite.scala:1424)
> 	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
> 	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
> 	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
> 	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
> 	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
> 	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite.org$scalatest$BeforeAndAfterAll$$super$run(LogisticRegressionSuite.scala:45)
> 	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
> 	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
> 	at org.apache.spark.ml.classificatiion.ps.LogisticRegressionSuite.run(LogisticRegressionSuite.scala:45)
> 	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
> 	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
> 	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
> 	at scala.collection.immutable.List.foreach(List.scala:381)
> 	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
> 	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
> 	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
> 	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
> 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
> 	at org.scalatest.tools.Runner$.run(Runner.scala:883)
> 	at org.scalatest.tools.Runner.run(Runner.scala)
> 	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
> 	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
> ```
> 
> It seems i need to config some libpath in the ide? Can you tell what i need to do or give me some tutorial about it.
> THX

Could you please tell me you how you configure the spark.yarn.queue, I encountered the same error result with yours, which file should I change to set `spark.yarn.queue`. Thank you very much.

**Comment by hbghhy** [comment]
> > 1. `SONA-example-local` is a local mode for Spark on Angel, the problem which the progress can not finished by itself has fix in the latest version.
> >    The error when you run `SONA-example`  is `submitted by user h to unknown queue: root.default`, because there is no queue named `root.default` in your yarn cluster, you must set `spark.yarn.queue` parameter, which is given `root.default` as default value in our system.
> > 2. Please have a look at `AngelPSContextSuite`, which can run successfully in IDEA.
> 
> I encountered the same issue, where should I set the spark.yarn.queue, could you please tell me in which file to set the "spark.yarn.queue"?
> I added the`--queue root.default \`in the SONA-example file, but the task still failed. Thank you very much.

You can see the code in spark-on-angel/core/src/main/scala/com/tencent/angel/spark/context/AngelPSContext.scala. 

`val queue = conf.get("spark.yarn.queue", "root.default")`

So, you need set a queue for your job when u submit. For example as below, the $UR_QUE will depends on ur yarn config. If u cannot find, just google how to manager queue in yarn.
```
source ./spark-on-angel-env.sh

$SPARK_HOME/bin/spark-submit \
    --jars $SONA_SPARK_JARS \
    --conf spark.yarn.queue $UR_QUE \
    --name "BreezeSGD-spark-on-angel" \
    --class com.tencent.angel.spark.examples.ml.BreezeSGD \
    ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar
```

**Comment by JessicaAlphy** [comment]
Thank you so much for helping me with my issue. I will attempt to configrue the spark.yarn.queue as you told me. Thanks again. Best regards. Jessica.------------------ 原始邮件 ------------------
发件人: "hbghhy"<notifications@github.com>
发送时间: 2019年6月23日(星期天) 晚上7:51
收件人: "Angel-ML/angel"<angel@noreply.github.com>;
抄送: "JessicaAlphy"<294731597@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Angel-ML/angel] Some problem of the example of spark on angel (#160)


   
SONA-example-local is a local mode for Spark on Angel, the problem which the progress can not finished by itself has fix in the latest version.
 The error when you run SONA-example  is submitted by user h to unknown queue: root.default, because there is no queue named root.default in your yarn cluster, you must set spark.yarn.queue parameter, which is given root.default as default value in our system.
 
Please have a look at AngelPSContextSuite, which can run successfully in IDEA.
   
I encountered the same issue, where should I set the spark.yarn.queue, could you please tell me in which file to set the "spark.yarn.queue"?
 I added the--queue root.default \in the SONA-example file, but the task still failed. Thank you very much.
  
You can see the code in spark-on-angel/core/src/main/scala/com/tencent/angel/spark/context/AngelPSContext.scala.
 
val queue = conf.get("spark.yarn.queue", "root.default")
 
So, you need set a queue for your job when u submit. For example as below, the $UR_QUE will depends on ur yarn config. If u cannot find, just google how to manager queue in yarn.
 source ./spark-on-angel-env.sh SONA_SPARK_JARS \     --conf spark.yarn.queue $UR_QUE \     --name "BreezeSGD-spark-on-angel" \     --class com.tencent.angel.spark.examples.ml.BreezeSGD \     ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar  
&mdash;
