### ISSUE TITLE
运行错误的问题，看不懂哪错了

### ISSUE THREAD

**Issue by alwayschasing** [Tencent/angel#19]
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
        at com.tencent.angel.client.yarn.AngelYarnClient.updateMaster(AngelYarnClient.java:493)
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:165)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:46)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
        at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:90)
        at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:28)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:124)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:110)
com.tencent.angel.exception.AngelException: java.io.IOException: Failed to run job : Application application_1496819712324_39810 failed 2 times due to AM Container for appattempt_1496819712324_39810_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://103.26.158.31:54315/proxy/application_1496819712324_39810/Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_1496819712324_39810_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:171)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:46)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
        at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:90)
        at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:28)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:124)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1656)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:110)

**Comment by paynie** [comment]
Thanks for reports these issues. You can try to find error message in logs. You can find methods in [FAQ](https://github.com/Tencent/angel/wiki/Angel%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by paynie** [comment]
This problem seems that the Yarn startup AppMaster failed, you can find error message in Master log.
