### ISSUE TITLE
run LR demo on yarn mode failed

### ISSUE THREAD

**Issue by yangjiamu** [Tencent/angel#202]
**the console log:**
java.io.IOException: Failed to run job : Application application_1504840963521_3755 failed 2 times due to AM Container for appattempt_1504840963521_3755_000002 exited with  exitCode: 1
For more detailed output, check the application tracking page: http://****/cluster/app/application_1504840963521_3755 Then click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e07_1504840963521_3755_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:933)
        at org.apache.hadoop.util.Shell.run(Shell.java:844)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:1123)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:237)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:317)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.

**log file**
2017-09-13 20:08:41,876 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class com.tencent.angel.master.ps.ParameterServerManagerEventType for class com.tencent.angel.master.ps.ParameterServerManager
2017-09-13 20:08:41,877 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class com.tencent.angel.master.ps.ps.AMParameterServerEventType for class com.tencent.angel.master.AngelApplicationMaster$ParameterServerEventHandler
2017-09-13 20:08:41,878 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class com.tencent.angel.master.ps.attempt.PSAttemptEventType for class com.tencent.angel.master.AngelApplicationMaster$PSAttemptEventDispatcher
2017-09-13 20:08:41,878 INFO [main] com.tencent.angel.master.AngelApplicationMaster: build PSManager success
2017-09-13 20:08:41,883 FATAL [main] com.tencent.angel.master.AngelApplicationMaster: Error starting AppMaster
java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/lib/input/CombineTextInputFormat
	at com.tencent.angel.conf.AngelConf.<clinit>(AngelConf.java:79)
	at com.tencent.angel.master.AngelApplicationMaster$RunningAppContext.getRunningMode(AngelApplicationMaster.java:323)
	at com.tencent.angel.master.AngelApplicationMaster.initAndStart(AngelApplicationMaster.java:678)
	at com.tencent.angel.master.AngelApplicationMaster$1.run(AngelApplicationMaster.java:589)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1865)
	at com.tencent.angel.master.AngelApplicationMaster.main(AngelApplicationMaster.java:586)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapreduce.lib.input.CombineTextInputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

my environment is hdp 2.5.5.0-157
my HADOOP_HOME is set to /usr/hdp/2.5.5.0-157/hadoop
my spark hdfs all work well

**Comment by paynie** [comment]
Can you find org/apache/hadoop/mapreduce/lib/input/CombineTextInputFormat in your hadoop jars?

**Comment by yangjiamu** [comment]
I wrote a hadoop mapreduce tests contains org/apache/hadoop/mapreduce/lib/input/CombineTextInputFormat and run successfully, i think there is environment problem but can't find where is wrong.

**Comment by paynie** [comment]
Do you set "yarn.application.classpath" or "mapreduce.application.classpath" options in your hadoop config files(yarn-site.xml, hdfs-site.xml and mapred-site.xml) ?

**Comment by yangjiamu** [comment]
I looked my conf file, yarn.application.classpath is setted in yarn-site.xml and mapreduce.application.classpath is not, in hdfs-site.xml both yarn.application.classpath and mapreduce.application.classpath are not setted, yarn.application.classpath is not setted in mapred-site.xml and mapreduce.application.classpath is setted. Should i set the yarn.application.classpath and mapreduce.application.classpath same in the three files?

**Comment by paynie** [comment]
OK， you can try like this: set "mapreduce.application.classpath" in angel-site.xml as same as in mapred-site.xml

**Comment by SamuelDSR** [comment]
一样的问题，设置了"mapreduce.application.classpath"之后还是不行

**Comment by Phoenixinfire** [comment]
有人解决了吗？has anybody solved this issue?
