### ISSUE TITLE
run angel on yarn failed, Exception from container-launch.

### ISSUE THREAD

**Issue by plorylmw** [Tencent/angel#234]
Hi,communities~
I tried to run angel on yarn but failed.(hadoop version: 2.6.0)

The Diagnostics:
Application application_1508939776983_0001 failed 2 times due to AM Container for appattempt_1508939776983_0001_000002 exited with exitCode: 1
For more detailed output, check application tracking page:http://114.212.189.79:50030/proxy/application_1508939776983_0001/Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_1508939776983_0001_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
at org.apache.hadoop.util.Shell.run(Shell.java:455)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.

Hope for your help, thank you!

**Comment by WisonHuang** [comment]
Hi,plorylmw. Have you succeed in running your submit in "LOCAL" mode. If not, I think LOCAL mode could give you more inforamtion about your problem.
Futuremore , the YARN mode needs you cluster installed on jdk8 environment, make sure your hadoop cluster environment is right.
