### ISSUE TITLE
lda* deal with big data, stuck

### ISSUE THREAD

**Issue by WisonHuang** [Tencent/angel#242]
Hi all,
I am using lda* to deal with some big data(60g).And the vocabulary is less than 2000000, and topic number is set to 8000. The resource config is as below:
![image](https://user-images.githubusercontent.com/6241452/32362385-d7c8f9fe-c0a3-11e7-80d2-0ced27c481d3.png)

With more than 12 hours running, it still stuck in the third iteration.
Here is the my submitting-client printing log:
![image](https://user-images.githubusercontent.com/6241452/32362269-028377ba-c0a3-11e7-9ec8-7b36aca19441.png)
Hers is the ps stdout log:
```
84K), 0.0265646 secs] 2728627K->1166343K(15164096K), 0.0267021 secs] [Times: user=0.18 sys=0.35, real=0.03 secs] 
57727.720: [GC (Allocation Failure) 57727.721: [ParNew: 1573119K->139K(1763584K), 0.0390621 secs] 2734023K->1161043K(15164096K), 0.0392322 secs] [Times: user=0.41 sys=0.03, real=0.04 secs] 
57779.217: [GC (Allocation Failure) 57779.217: [ParNew: 1567819K->115K(1763584K), 0.0242208 secs] 2728723K->1161018K(15164096K), 0.0243295 secs] [Times: user=0.36 sys=0.01, real=0.03 secs] 
57830.650: [GC (Allocation Failure) 57830.650: [ParNew: 1567795K->110K(1763584K), 0.0192676 secs] 2728698K->1161014K(15164096K), 0.0193749 secs] [Times: user=0.25 sys=0.06, real=0.02 secs] 
57883.123: [GC (Allocation Failure) 57883.123: [ParNew: 1567790K->110K(1763584K), 0.0222742 secs] 2728694K->1161014K(15164096K), 0.0223973 secs] [Times: user=0.33 sys=0.03, real=0.02 secs] 
57935.562: [GC (Allocation Failure) 57935.562: [ParNew: 1567790K->110K(1763584K), 0.0248337 secs] 2728694K->1161014K(15164096K), 0.0249438 secs] [Times: user=0.20 sys=0.30, real=0.02 secs] 
57986.883: [GC (Allocation Failure) 57986.883: [ParNew: 1567790K->40K(1763584K), 0.0150539 secs] 2728694K->1161009K(15164096K), 0.0151627 secs] [Times: user=0.22 sys=0.01, real=0.02 secs] 
58037.778: [GC (Allocation Failure) 58037.778: [ParNew: 1567720K->46K(1763584K), 0.0255322 secs] 2728689K->1161016K(15164096K), 0.0256587 secs] [Times: user=0.21 sys=0.33, real=0.02 secs] 
58089.445: [GC (Allocation Failure) 58089.445: [ParNew: 1567726K->46K(1763584K), 0.0173600 secs] 2728696K->1161016K(15164096K), 0.0174657 secs] [Times: user=0.26 sys=0.03, real=0.02 secs] 
58143.698: [GC (Allocation Failure) 58143.698: [ParNew: 1567726K->42K(1763584K), 0.0199756 secs] 2728696K->1161012K(15164096K), 0.0200898 secs] [Times: user=0.25 sys=0.08, real=0.02 secs] 
58195.754: [GC (Allocation Failure) 58195.754: [ParNew: 1567722K->42K(1763584K), 0.0138952 secs] 2728692K->1161012K(15164096K), 0.0140011 secs] [Times: user=0.22 sys=0.03, real=0.02 secs] 
58247.830: [GC (Allocation Failure) 58247.830: [ParNew: 1567722K->44K(1763584K), 0.0246098 secs] 2728692K->1161014K(15164096K), 0.0247217 secs] [Times: user=0.30 sys=0.13, real=0.02 secs] 
58299.705: [GC (Allocation Failure) 58299.705: [ParNew: 1567724K->44K(1763584K), 0.0168798 secs] 2728694K->1161014K(15164096K), 0.0170165 secs] [Times: user=0.28 sys=0.01, real=0.02 secs] 
58334.775: [GC (Allocation Failure) 58334.775: [ParNew: 1567724K->5371K(1763584K), 0.0212361 secs] 2728694K->1166342K(15164096K), 0.0213374 secs] [Times: user=0.26 sys=0.11, real=0.02 secs] 
58367.146: [GC (Allocation Failure) 58367.146: [ParNew: 1573051K->5376K(1763584K), 0.0149972 secs] 2734022K->1166346K(15164096K), 0.0151005 secs] [Times: user=0.25 sys=0.05, real=0.02 secs] 
58418.172: [GC (Allocation Failure) 58418.172: [ParNew: 1573056K->115K(1763584K), 0.0238081 secs] 2734026K->1161085K(15164096K), 0.0239061 secs] [Times: user=0.21 sys=0.28, real=0.02 secs] 
58470.388: [GC (Allocation Failure) 58470.388: [ParNew: 1567795K->110K(1763584K), 0.0209450 secs] 2728765K->1161081K(15164096K), 0.0210651 secs] [Times: user=0.29 sys=0.01, real=0.02 secs] 
58522.478: [GC (Allocation Failure) 58522.479: [ParNew: 1567790K->112K(1763584K), 0.0130606 secs] 2728761K->1161083K(15164096K), 0.0131714 secs] [Times: user=0.21 sys=0.01, real=0.01 secs] 
58574.378: [GC (Allocation Failure) 58574.379: [ParNew: 1567792K->110K(1763584K), 0.0249262 secs] 2728763K->1161081K(15164096K), 0.0250254 secs] [Times: user=0.23 sys=0.26, real=0.02 secs] 
58628.381: [GC (Allocation Failure) 58628.381: [ParNew: 1567790K->44K(1763584K), 0.0120966 secs] 2728761K->1161082K(15164096K), 0.0121955 secs] [Times: user=0.22 sys=0.02, real=0.01 secs] 
58680.263: [GC (Allocation Failure) 58680.263: [ParNew: 1567724K->46K(1763584K), 0.0254905 secs] 2728762K->1161083K(15164096K), 0.0255982 secs] [Times: user=0.26 sys=0.24, real=0.03 secs] 
58733.567: [GC (Allocation Failure) 58733.567: [ParNew: 1567726K->40K(1763584K), 0.0198921 secs] 2728763K->1161078K(15164096K), 0.0199887 secs] [Times: user=0.26 sys=0.05, real=0.02 secs] 
```

Here is the  worker stdout log:
```
Showing 4096 bytes. Click here for full log
), 0.0411663 secs] [Times: user=0.55 sys=0.24, real=0.05 secs] 
56986.336: [GC (Allocation Failure) 56986.336: [ParNew: 2262349K->12296K(2530368K), 0.0402145 secs] 3594537K->1345162K(15078912K), 0.0403913 secs] [Times: user=0.51 sys=0.48, real=0.04 secs] 
57047.233: [GC (Allocation Failure) 57047.233: [ParNew: 2261576K->12485K(2530368K), 0.0423051 secs] 3594442K->1346061K(15078912K), 0.0424874 secs] [Times: user=0.60 sys=0.15, real=0.04 secs] 
57108.543: [GC (Allocation Failure) 57108.543: [ParNew: 2261765K->13907K(2530368K), 0.0735100 secs] 3595341K->1348199K(15078912K), 0.0737216 secs] [Times: user=0.67 sys=0.09, real=0.07 secs] 
57169.522: [GC (Allocation Failure) 57169.522: [ParNew: 2263187K->13681K(2530368K), 0.0390400 secs] 3597479K->1348678K(15078912K), 0.0392159 secs] [Times: user=0.51 sys=0.23, real=0.04 secs] 
57230.121: [GC (Allocation Failure) 57230.121: [ParNew: 2262961K->12987K(2530368K), 0.0414543 secs] 3597958K->1348679K(15078912K), 0.0416370 secs] [Times: user=0.55 sys=0.24, real=0.04 secs] 
57291.592: [GC (Allocation Failure) 57291.592: [ParNew: 2262267K->12825K(2530368K), 0.0599375 secs] 3597959K->1349246K(15078912K), 0.0601280 secs] [Times: user=0.71 sys=0.57, real=0.06 secs] 
57352.691: [GC (Allocation Failure) 57352.691: [ParNew: 2262105K->13610K(2530368K), 0.0593013 secs] 3598526K->1350739K(15078912K), 0.0595060 secs] [Times: user=0.54 sys=0.26, real=0.06 secs] 
57413.388: [GC (Allocation Failure) 57413.388: [ParNew: 2262890K->13639K(2530368K), 0.0525071 secs] 3600019K->1351480K(15078912K), 0.0526886 secs] [Times: user=0.35 sys=1.06, real=0.06 secs] 
57473.995: [GC (Allocation Failure) 57473.995: [ParNew: 2262919K->13164K(2530368K), 0.0425444 secs] 3600760K->1351710K(15078912K), 0.0427320 secs] [Times: user=0.34 sys=0.77, real=0.05 secs] 
57535.005: [GC (Allocation Failure) 57535.005: [ParNew: 2262444K->13144K(2530368K), 0.0442501 secs] 3600990K->1352412K(15078912K), 0.0444258 secs] [Times: user=0.43 sys=0.72, real=0.05 secs] 
57596.018: [GC (Allocation Failure) 57596.018: [ParNew: 2262424K->12793K(2530368K), 0.0374606 secs] 3601692K->1352765K(15078912K), 0.0376788 secs] [Times: user=0.56 sys=0.31, real=0.04 secs] 
57657.030: [GC (Allocation Failure) 57657.030: [ParNew: 2262073K->12718K(2530368K), 0.0368377 secs] 3602045K->1353407K(15078912K), 0.0370679 secs] [Times: user=0.46 sys=0.45, real=0.03 secs] 
57718.455: [GC (Allocation Failure) 57718.455: [ParNew: 2261998K->12727K(2530368K), 0.0378818 secs] 3602687K->1354120K(15078912K), 0.0380562 secs] [Times: user=0.55 sys=0.23, real=0.04 secs] 
57782.176: [GC (Allocation Failure) 57782.177: [ParNew: 2262007K->12400K(2530368K), 0.0481664 secs] 3603400K->1354518K(15078912K), 0.0484052 secs] [Times: user=0.48 sys=0.62, real=0.05 secs] 
57847.960: [GC (Allocation Failure) 57847.960: [ParNew: 2261680K->12958K(2530368K), 0.0484683 secs] 3603798K->1355792K(15078912K), 0.0486566 secs] [Times: user=0.40 sys=0.87, real=0.05 secs] 
57916.325: [GC (Allocation Failure) 57916.325: [ParNew: 2262238K->12336K(2530368K), 0.0481672 secs] 3605072K->1355880K(15078912K), 0.0483547 secs] [Times: user=0.35 sys=0.91, real=0.05 secs] 
57981.412: [GC (Allocation Failure) 57981.413: [ParNew: 2261616K->12747K(2530368K), 0.0546903 secs] 3605160K->1357008K(15078912K), 0.0548650 secs] [Times: user=0.46 sys=1.04, real=0.05 secs] 
58066.669: [GC (Allocation Failure) 58066.669: [ParNew: 2262027K->14678K(2530368K), 0.0495294 secs] 3606288K->1359667K(15078912K), 0.0497158 secs] [Times: user=0.65 sys=0.24, real=0.05 secs] 
58134.991: [GC (Allocation Failure) 58134.991: [ParNew: 2263958K->13101K(2530368K), 0.0536905 secs] 3608947K->1358797K(15078912K), 0.0538956 secs] [Times: user=0.63 sys=0.15, real=0.05 secs] 
58206.604: [GC (Allocation Failure) 58206.604: [ParNew: 2262381K->13396K(2530368K), 0.0492966 secs] 3608077K->1359790K(15078912K), 0.0494558 secs] [Times: user=0.60 sys=0.66, real=0.05 secs] 
58270.487: [GC (Allocation Failure) 58270.487: [ParNew: 2262676K->12970K(2530368K), 0.0426990 secs] 3609070K->1360076K(15078912K), 0.0428831 secs] [Times: user=0.43 sys=0.65, real=0.05 secs] 
```
According to the log, it seems that the problem always "GC Allocation Failure".
Anyone has any idea with this? THX!

**Comment by leleyu** [comment]
The "GC Allocation Failure is not a problem". Can you see the "progress" page to check out 
which worker is the slowest one ? And is there any error in the worker syslog  or stderr?

**Comment by WisonHuang** [comment]
@leleyu THX leleyu. There do has a slowest worker . And the stderr logs show as follow:
```
o.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 15435038720, max: 15440805888)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:252)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 15435038720, max: 15440805888)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:592)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:546)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:699)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:688)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:372)
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:120)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:263)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1066)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1058)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1048)
	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:246)
	... 15 more
```
I think maybe some document size is too large ,that cases out of memory.
I will limit the document size, and try again later.
THX again.

**Comment by leleyu** [comment]
This is weird since this error shows that you have consumed about 15GB direct memory.
The direct memory is used to communication between workers and servers, not for storing
the documents.
I think you can increase the number of partitions or limit the network transfer bytes
by setting the value of “angel.network.max.bytes.flight”. The default value for this one
is about 1GB. I think you should lower it to about 100MB or more smaller.
