### ISSUE TITLE
GBDTLocalExample-predict exception: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by marshalWS** [Tencent/angel#255]
17/11/22 11:05:28 INFO GBDT.GBDTModel : Tree[1] node predictions: 0.0,0.0,0.0
17/11/22 11:06:30 ERROR task.Task : task runner error
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacity(ArrayList.java:218)
	at com.tencent.angel.worker.storage.MemoryDataBlock.estimateAndResizeVList(MemoryDataBlock.java:155)
	at com.tencent.angel.worker.storage.MemoryDataBlock.put(MemoryDataBlock.java:95)
	at com.tencent.angel.ml.GBDT.GBDTModel$$anonfun$predict$4.apply$mcVI$sp(GBDTModel.scala:199)
	at com.tencent.angel.ml.GBDT.GBDTModel$$anonfun$predict$4.apply(GBDTModel.scala:171)
	at com.tencent.angel.ml.GBDT.GBDTModel$$anonfun$predict$4.apply(GBDTModel.scala:171)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at com.tencent.angel.ml.GBDT.GBDTModel.predict(GBDTModel.scala:171)
	at com.tencent.angel.ml.task.PredictTask.predict(PredictTask.scala:46)
	at com.tencent.angel.ml.GBDT.GBDTPredictTask.predict(GBDTPredictTask.scala:29)
	at com.tencent.angel.ml.task.PredictTask.run(PredictTask.scala:39)
	at com.tencent.angel.worker.task.Task.runUser(Task.java:94)
	at com.tencent.angel.worker.task.Task.run(Task.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marshalWS** [comment]
maxStoreNum:2759410 is correct, maxStoreNum:37449142 is error. 
The data is :F:\angel-master\angel-ps\data\exampledata\GBDTLocalExampleData\
 agaricus.txt.train agaricus.txt.test

17/11/22 11:46:24 INFO storage.MemoryDataBlock : *****************maxStoreNum:2759410
17/11/22 11:46:24 INFO model.PSModel : After training matrix gbdt.node.predict will be saved to file:///C:\Users\ADMINI~1\AppData\Local\Temp\/out
17/11/22 11:46:24 INFO model.PSModel : After training matrix gbdt.split.value will be saved to file:///C:\Users\ADMINI~1\AppData\Local\Temp\/out
17/11/22 11:46:24 INFO model.PSModel : After training matrix gbdt.split.feature will be saved to file:///C:\Users\ADMINI~1\AppData\Local\Temp\/out
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[0] split feature: 0,0,0
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[0] split value: 0.0,0.0,0.0
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[0] node predictions: 0.0,0.0,0.0
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[1] split feature: 0,0,0
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[1] split value: 0.0,0.0,0.0
17/11/22 11:46:24 INFO GBDT.GBDTModel : Tree[1] node predictions: 0.0,0.0,0.0
17/11/22 11:46:24 INFO storage.MemoryDataBlock : *****************maxStoreNum:37449142
17/11/22 11:46:24 ERROR task.Task : task runner error
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacity(ArrayList.java:218)

**Comment by marshalWS** [comment]
I know it. The JVM Xmx is too small!

**Comment by leleyu** [comment]
If you run angel with Local mode, all things are running in one JVM.
The bin/angel-example script start a JVM. You can set the size of JVM by add -Xmx8g in this script.
