### ISSUE TITLE
yarn集群demo运行失败

### ISSUE THREAD

**Issue by tankle** [Tencent/angel#265]
Application application_1510661908139_1158827 failed 2 times due to AM Container for appattempt_1510661908139_1158827_000002 exited with exitCode: 127
For more detailed output, check application tracking page:http://xx/cluster/app/application_1510661908139_1158827Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e04_1510661908139_1158827_02_000001
Exit code: 127
Stack trace: ExitCodeException exitCode=127:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:593)
at org.apache.hadoop.util.Shell.run(Shell.java:490)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:784)
at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:298)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:324)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Shell output: main : command provided 1
main : user is xxx
main : requested yarn user is xxx
Container exited with a non-zero exit code 127
Failing this attempt. Failing the application.

**Comment by paynie** [comment]
Hadoop env has some problem, maybe some jars not been found. You can find the detail log in Master log using the method in https://github.com/Tencent/angel/wiki/%E5%B7%A5%E7%A8%8B%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
