### ISSUE TITLE
单机LDA训练700mb左右数据出错

### ISSUE THREAD

**Issue by Coffeexiudou** [Tencent/angel#280]
18/01/09 15:20:09 INFO lda.LDALearner: epoch=2 local likelihood=-1.593743188359314E9
18/01/09 15:20:09 INFO lda.LDALearner: save word topic
18/01/09 15:20:09 INFO metrics.MetricsService: Epoch=6 Metrics={"log.likelihood":"-1593743000.000000"}
18/01/09 15:20:10 INFO client.AngelClient: Epoch: 6. Metrics={"log.likelihood":-1593743000.000000}
18/01/09 15:21:19 FATAL transport.MatrixTransportClient: hanlder rpc response failed 
java.lang.OutOfMemoryError: Java heap space
	at com.tencent.angel.ps.impl.matrix.ServerDenseIntRow.<init>(ServerDenseIntRow.java:67)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRow(ServerPartition.java:186)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRows(ServerPartition.java:163)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.<init>(ServerPartition.java:68)
	at com.tencent.angel.psagent.matrix.cache.MatrixCache.update(MatrixCache.java:133)
	at com.tencent.angel.psagent.matrix.cache.MatricesCache.update(MatricesCache.java:223)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.updateMatrixCache(MatrixTransportClient.java:1657)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.handleGetRowsSplitResponse(MatrixTransportClient.java:1596)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.run(MatrixTransportClient.java:1437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/01/09 15:22:29 FATAL transport.MatrixTransportClient: hanlder rpc response failed 
java.lang.OutOfMemoryError: Java heap space
	at com.tencent.angel.ps.impl.matrix.ServerDenseIntRow.<init>(ServerDenseIntRow.java:67)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRow(ServerPartition.java:186)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRows(ServerPartition.java:163)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.<init>(ServerPartition.java:68)
	at com.tencent.angel.psagent.matrix.cache.MatrixCache.update(MatrixCache.java:133)
	at com.tencent.angel.psagent.matrix.cache.MatricesCache.update(MatricesCache.java:223)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.updateMatrixCache(MatrixTransportClient.java:1657)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.handleGetRowsSplitResponse(MatrixTransportClient.java:1596)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.run(MatrixTransportClient.java:1437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/01/09 15:22:30 WARN hdfs.DFSClient: Slow waitForAckedSeqno took 43787ms (threshold=30000ms)
18/01/09 15:21:44 FATAL transport.MatrixTransportClient: hanlder rpc response failed 
java.lang.OutOfMemoryError: Java heap space
	at com.tencent.angel.ps.impl.matrix.ServerDenseIntRow.<init>(ServerDenseIntRow.java:67)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRow(ServerPartition.java:186)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRows(ServerPartition.java:163)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.<init>(ServerPartition.java:68)
	at com.tencent.angel.psagent.matrix.cache.MatrixCache.update(MatrixCache.java:133)
	at com.tencent.angel.psagent.matrix.cache.MatricesCache.update(MatricesCache.java:223)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.updateMatrixCache(MatrixTransportClient.java:1657)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.handleGetRowsSplitResponse(MatrixTransportClient.java:1596)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.run(MatrixTransportClient.java:1437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/01/09 15:21:32 WARN hdfs.DFSClient: DFSOutputStream ResponseProcessor exception  for block BP-1778593106-127.0.1.1-1515377011140:blk_1073743400_2584
java.io.EOFException: Premature EOF: no length prefix available
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2294)
	at org.apache.hadoop.hdfs.protocol.datatransfer.PipelineAck.readFields(PipelineAck.java:244)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer$ResponseProcessor.run(DFSOutputStream.java:847)
18/01/09 15:21:20 FATAL transport.MatrixTransportClient: hanlder rpc response failed 
java.lang.OutOfMemoryError: Java heap space
	at com.tencent.angel.ps.impl.matrix.ServerDenseIntRow.<init>(ServerDenseIntRow.java:67)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRow(ServerPartition.java:186)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.initRows(ServerPartition.java:163)
	at com.tencent.angel.ps.impl.matrix.ServerPartition.<init>(ServerPartition.java:68)
	at com.tencent.angel.psagent.matrix.cache.MatrixCache.update(MatrixCache.java:133)
	at com.tencent.angel.psagent.matrix.cache.MatricesCache.update(MatricesCache.java:223)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.updateMatrixCache(MatrixTransportClient.java:1657)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.handleGetRowsSplitResponse(MatrixTransportClient.java:1596)
	at com.tencent.angel.psagent.matrix.transport.MatrixTransportClient$Responser.run(MatrixTransportClient.java:1437)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
18/01/09 15:22:30 INFO psagent.PSAgent: psagent falied

单机伪分布式只有一个结点，内存有16g,数据只有700多mb，angel.ps.java.opts，angel.am.java.opts等等这些都设置的很大了，训练完后save的时候报错，不明白到底是哪里占用了内存，HADOOP_OPTS="-Xmx10000m"设置的很大，但都占满了(很小白。。求帮助）

 ./angel-submit --action.type train 
--angel.deploy.mode LOCAL
 --angel.app.submit.class com.tencent.angel.ml.lda.LDARunner
 --angel.train.data.path "hdfs://coffee:9000/test/trainData1" 
 --angel.save.model.path "hdfs://coffee:9000/test/output"
 --angel.log.path "hdfs://coffee:9000/test/log" 
--save.doc.topic true 
--ml.epoch.num 2 
--ml.lda.word.num 1462503 
--ml.lda.topic.num 1000 
--ml.lda.alpha 0.05 --ml.lda.beta 0.01 
--save.word.topic true
 --ml.worker.thread.num ８
 --angel.am.java.opts -Xmx8192m 
--angel.ps.java.opts -Xm8192m

**Comment by leleyu** [comment]
When saving, worker needs to pull the whole word-topic matrix from server. 
The whole memory is about 1462503*1000*4 = 5.44GB.
Currently this one is stored by dense format. 
I will commit a sparse one later to fix this problem.

**Comment by sdubrother** [comment]
is the problem fixed?

**Comment by sdubrother** [comment]
> When saving, worker needs to pull the whole word-topic matrix from server.
> The whole memory is about 1462503x1000x4 = 5.44GB.
> Currently this one is stored by dense format.
> I will commit a sparse one later to fix this problem.

is the problem sloved?

**Comment by leleyu** [comment]
It's solved on branch-2.0.0.
