### ISSUE TITLE
Got error when submitting on yarn

### ISSUE THREAD

**Issue by loverofvenus** [Tencent/angel#291]
I got an error when I tried to submit tasks on yarn and can not find any other messages about this error.

AppMaster capability = <memory:2048, vCores:1>
18/01/23 20:47:40 INFO yarn.AngelYarnClient: Command to launch container for ApplicationMaster is : $JAVA_HOME/bin/java -Dlog4j.configuration=log/angel.properties -Dlog4j.logger.com.tencent.ml=DEBUG -Dyarn.app.container.log.dir=<LOG_DIR> -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA  -Xmx1536M -Xms1536M -XX:PermSize=100M -XX:MaxPermSize=200M com.tencent.angel.master.AngelApplicationMaster 1><LOG_DIR>/stdout 2><LOG_DIR>/stderr 
18/01/23 20:47:40 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  xxxx
18/01/23 20:47:40 INFO impl.YarnClientImpl: Submitted application application_1516343220217_193019
18/01/23 20:47:54 ERROR yarn.AngelYarnClient: submit application to yarn failed.
java.io.IOException: Failed to run job : Application application_1516343220217_193019 failed 2 times due to AM Container for appattempt_1516343220217_193019_000002 exited with  exitCode: 1
For more detailed output, check application tracking page:http://nodexxxx:8808/proxy/application_1516343220217_193019/Then, click on links to logs of each attempt.
Diagnostics: Exception from container-launch.
Container id: container_e14_1516343220217_193019_02_000001
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:601)
        at org.apache.hadoop.util.Shell.run(Shell.java:504)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:786)
        at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:373)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Shell output: main : command provided 1
main : run as user is xxxx
main : requested yarn user is xxxx
Writing to tmp file /data10/yarn/local/nmPrivate/application_1516343220217_193019/container_e14_1516343220217_193019_02_000001/container_e14_1516343220217_193019_02_000001.pid.tmp

**Comment by zhaochunhua** [comment]
碰到一样的问题，能分享下怎么解决的吗？
