### ISSUE TITLE
NPE happen for heartbeat check

### ISSUE THREAD

**Issue by paynie** [Tencent/angel#331]
===== FINISHED com.tencent.angel.spark.ops.VectorOpsSuite: 'doFill' ======

[32m- doFill[0m
[32mCachedPSVectorSuite:[0m
Exception in thread "Heartbeat Timeout checker" java.lang.NullPointerException
	at com.tencent.angel.master.HeartbeatMonitor$1.run(HeartbeatMonitor.java:62)
	at java.lang.Thread.run(Thread.java:748)

**Comment by paynie** [comment]
resloved
