### ISSUE TITLE
Assign container failed

### ISSUE THREAD

**Issue by paynie** [Tencent/angel#334]
2018-04-27 11:33:57,629 ERROR [RMCommunicator Allocator] com.tencent.angel.master.deploy.ContainerAllocator: send heartbeat to rm failed. 
java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1439)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.assignContainers(YarnContainerAllocator.java:813)
        at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.heartbeat(YarnContainerAllocator.java:331)
        at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator.access$500(YarnContainerAllocator.java:76)
        at com.tencent.angel.master.deploy.yarn.YarnContainerAllocator$1.run(YarnContainerAllocator.java:238)
        at java.lang.Thread.run(Thread.java:745)

**Comment by paynie** [comment]
Resolved in 1.5.1
