### ISSUE TITLE
run SONA-example-local, throw the IOException. When spark-submit.sh sumbit job, how to set angel.log.path?

### ISSUE THREAD

**Issue by liuzx32** [Tencent/angel#342]
18/05/08 12:27:09 ERROR MetricsService: init log writter failed
java.io.IOException: log directory is null. you must set angel.log.path
	at com.tencent.angel.master.metrics.DistributeLog.init(DistributeLog.java:68)
	at com.tencent.angel.master.metrics.MetricsService.serviceInit(MetricsService.java:111)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:107)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at com.tencent.angel.master.AngelApplicationMaster.initAndStart(AngelApplicationMaster.java:771)
	at com.tencent.angel.localcluster.LocalMaster.run(LocalMaster.java:63)

**Comment by ZunwenYou** [comment]
try set spark.hadoop.angel.log.path=/some/writtable/hdfs/path

**Comment by liuzx32** [comment]
Ok, Thanks! Add --conf spark.hadoop.angel.log.path=/some/writtable/hdfs/path to SNOA-example or SONA-example-local scripts.
