### ISSUE TITLE
java.io.IOException: wait for master location timeout

### ISSUE THREAD

**Issue by janelu9** [Tencent/angel#354]
when I run the BreezeSGD on spark yarn ,it throws this error but nothing wrong happened on local mode

**Comment by janelu9** [comment]
java.io.IOException: wait for master location timeout
        at com.tencent.angel.client.yarn.AngelYarnClient.updateMaster(AngelYarnClient.java:558)
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:168)
        at com.tencent.angel.client.AngelPSClient.startPS(AngelPSClient.java:98)
        at com.tencent.angel.spark.context.AngelPSContext$.launchAngel(AngelPSContext.scala:344)
        at com.tencent.angel.spark.context.AngelPSContext$.apply(AngelPSContext.scala:236)
        at com.tencent.angel.spark.context.PSContext$.liftedTree1$1(PSContext.scala:68)
        at com.tencent.angel.spark.context.PSContext$.instance(PSContext.scala:66)
        at com.tencent.angel.spark.context.PSContext$.getOrCreate(PSContext.scala:50)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:43)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
        at com.tencent.angel.spark.examples.util.SparkUtils$.runSpark(SparkUtils.scala:50)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:42)
        at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.Exception: init PSContext failed, com.tencent.angel.exception.AngelException: java.io.IOException: wait for master location timeout
        at com.tencent.angel.spark.context.PSContext$.getOrCreate(PSContext.scala:53)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:43)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$$anonfun$main$1.apply(BreezeSGD.scala:42)
        at com.tencent.angel.spark.examples.util.SparkUtils$.runSpark(SparkUtils.scala:50)
        at com.tencent.angel.spark.examples.ml.BreezeSGD$.main(BreezeSGD.scala:42)
        at com.tencent.angel.spark.examples.ml.BreezeSGD.main(BreezeSGD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by janelu9** [comment]
well i'have resolved this problem by enlarging the nodemanager-resource.memory

**Comment by wjlight** [comment]
@janelu9 hi,do you mean in yarn-site.yml add
```
<property>
<name>yarn.nodemanager.resource.memory-mb</name>
<value>8192</value>
</property>
```
?

**Comment by rogerBridge** [comment]
@wjlight  did you solved it?
