### ISSUE TITLE
I've just run angle LR on yarn model but failed,(centos 6.5 hadoop2.2  protobuf2.5 java1.8 hdfs and yarn  all can work well)

### ISSUE THREAD

**Issue by xxlest** [Tencent/angel#96]
17/06/25 00:23:54 INFO Configuration.deprecation: mapred.cache.files.filesizes is deprecated. Instead, use mapreduce.job.cache.files.filesizes
AppMaster capability = <memory:2048, vCores:1>
17/06/25 00:23:54 INFO yarn.AngelYarnClient: Command to launch container for ApplicationMaster is : $JAVA_HOME/bin/java -Dlog4j.configuration=log/angel.properties -Dlog4j.logger.com.tencent.ml=DEBUG -Dyarn.app.container.log.dir=<LOG_DIR> -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Xmx1024m com.tencent.angel.master.AngelApplicationMaster 1><LOG_DIR>/stdout 2><LOG_DIR>/stderr 
17/06/25 00:23:54 INFO yarn.AngelYarnClient: ApplicationSubmissionContext Queuename :  default
17/06/25 00:23:54 INFO impl.YarnClientImpl: Submitted application application_1498320278135_0001 to ResourceManager at master/10.211.55.19:8032
17/06/25 00:23:59 INFO yarn.AngelYarnClient: appMaster getTrackingUrl = master:8088/cluster/app/application_1498320278135_0001/
17/06/25 00:23:59 INFO yarn.AngelYarnClient: master host=10.211.55.22, port=25695
17/06/25 00:23:59 INFO yarn.AngelYarnClient: start to create rpc client to am
17/06/25 00:28:55 ERROR yarn.AngelYarnClient: submit application to yarn failed.
com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.211.55.22:25695
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:312)
        at com.sun.proxy.$Proxy10.getAllPSLocation(Unknown Source)
        at com.tencent.angel.client.AngelClient.waitForAllPS(AngelClient.java:710)
        at com.tencent.angel.client.yarn.AngelYarnClient.startPSServer(AngelYarnClient.java:167)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:46)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
        at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:90)
        at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:28)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:124)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:110)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.211.55.22:25695
        at com.tencent.angel.ipc.CallFuture.get(CallFuture.java:126)
        at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:462)
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:290)
        ... 14 more
Caused by: java.io.IOException: Error connecting to /10.211.55.22:25695
        at com.tencent.angel.ipc.NettyTransceiver.getChannel(NettyTransceiver.java:283)
        at com.tencent.angel.ipc.NettyTransceiver.writeDataPack(NettyTransceiver.java:535)
        at com.tencent.angel.ipc.NettyTransceiver.transceive(NettyTransceiver.java:505)
        at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:458)
        ... 15 more

**Comment by paynie** [comment]
Thanks for reports this issue. It seems that ps startup failed. You can find detail message in ps log use the method in [FAQ](https://github.com/Tencent/angel/wiki/Angel%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by xxlest** [comment]
thank your strong support , i fixed this issue by this  method "@wtx626 It seems that the netty jar can not found in hadoop env or the netty jar in hadoop env is too old, you can upload it by yourself. The method is following:
open the angel configure file(conf/angel-site.xml), add ${ANGEL_HOME}/lib/netty-all-4.1.1.Final.jar in angel.job.libjars lis"

**Comment by xxlest** [comment]
and now new issue is comming  create matrices failed. 
17/06/26 11:46:51 INFO yarn.AngelYarnClient: start to create rpc client to am
17/06/26 11:47:03 INFO yarn.AngelYarnClient: start pss success
17/06/26 11:47:03 INFO ps.PSPartitioner: blockRow = 1, blockCol=1024
17/06/26 11:47:03 INFO protobuf.ProtobufUtil: Matrix lr_weight partition num: 1
17/06/26 11:47:03 INFO ps.PSPartitioner: blockRow = 1, blockCol=50
17/06/26 11:47:03 INFO protobuf.ProtobufUtil: Matrix lr_loss partition num: 1
com.tencent.angel.exception.AngelException: create matrices failed.
        at com.tencent.angel.client.AngelClient.loadModel(AngelClient.java:166)
        at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:47)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:28)
        at com.tencent.angel.ml.classification.lr.LRRunner.train(LRRunner.scala:40)
        at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:90)
        at com.tencent.angel.ml.classification.lr.LRRunner.submit(LRRunner.scala:28)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:124)
        at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:110)
Caused by: com.google.protobuf.ServiceException: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.211.55.21:28735
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:312)
        at com.sun.proxy.$Proxy10.checkMatricesCreated(Unknown Source)
        at com.tencent.angel.client.AngelClient.waitForMatricesCreated(AngelClient.java:506)
        at com.tencent.angel.client.AngelClient.createMatrices(AngelClient.java:493)
        at com.tencent.angel.client.AngelClient.loadModel(AngelClient.java:164)
        ... 11 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Error connecting to /10.211.55.21:28735
        at com.tencent.angel.ipc.CallFuture.get(CallFuture.java:126)
        at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:462)
        at com.tencent.angel.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:290)
        ... 15 more
Caused by: java.io.IOException: Error connecting to /10.211.55.21:28735
        at com.tencent.angel.ipc.NettyTransceiver.getChannel(NettyTransceiver.java:283)
        at com.tencent.angel.ipc.NettyTransceiver.writeDataPack(NettyTransceiver.java:535)
        at com.tencent.angel.ipc.NettyTransceiver.transceive(NettyTransceiver.java:505)
        at com.tencent.angel.ipc.NettyTransceiver.call(NettyTransceiver.java:458)
        ... 16 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:148)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:104)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:78)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:41)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[hadoop@master bin]$

**Comment by paynie** [comment]
This is client log， you can paste master log here.

**Comment by paynie** [comment]
PS is killed as memory usage is over limit of the container allocated.

**Comment by xxlest** [comment]
@paynie thanks for your strong support, i this issue have been resolved, just set memory more than 2G for each work. thanks again.
